course/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template, redirect_to
from views import Exercise1

urlpatterns = patterns(
    '',

    url(r'^$',
        redirect_to, {'url': '/course/week1/'},
        name='home'),
    url(r'^week1/$',
        redirect_to, {'url': '/course/week1/lecture1/'},
        name='week1'),
    url(r'^week1/lecture1/$',
        direct_to_template, {'template': 'week1/lecture1.html'},
        name='week1/lecture1'),
    url(r'^week1/lecture2/$',
        direct_to_template, {'template': 'week1/lecture2.html'},
        name='week1/lecture2'),
    url(r'^week1/exercises/$',
        redirect_to, {'url': '/course/week1/exercises/1/'},
        name='week1/exercises'),
    url(r'^week1/exercises/1/$', Exercise1.as_view(),
        name='week1/exercises/1'),
    url(r'^week1/exercises/2/$', Exercise1.as_view(),
        name='week1/exercises/2'),
    url(r'^week1/lab/$',
        direct_to_template, {'template': 'week1/lab.html'},
        name='week1/lab'),
    url(r'^week1/lab/test-suite/$',
        direct_to_template, {'template': 'week1/lab-test-suite.html'},
        name='week1/lab/test-suite'),
    url(r'^week1/lab/submit/$',
        direct_to_template, {'template': 'week1/lab-submit.html'},
        name='week1/lab/submit'),
)

plt/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.simple import direct_to_template

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'plt.views.home', name='home'),
    url(r'^info/', direct_to_template, {'template': 'info.html'}, name='info'),
    url(r'^contact/', direct_to_template, {'template': 'contact.html'}, name='contact'),
    url(r'^course/', include('course.urls', namespace="course")),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

course/models.py
from django.db import models

# Create your models here.

course/views.py
from django.http import HttpResponse
import datetime
from django import forms
from django.views.generic.edit import FormView
from django.template import RequestContext

NO_ERROR = "0"
SYNTAX_ERROR = "1"
TYPE_ERROR = "2"
RUNTIME_ERROR = "3"

CODE_EXO1= (
    ("int main ()",                 RUNTIME_ERROR, "Main should have two arguments"),
    ("{",                           NO_ERROR,       ""),
    ("    int i ;",                 NO_ERROR,       ""),
    ("    int j = k + 1 ;",         TYPE_ERROR,     "k is undefined"),
    ("    int a[] = {1,2,3}",       SYNTAX_ERROR,   "Missing semi-column"),
    ("    j = a + 6 ;",             TYPE_ERROR,     "We can't add an array to an int"),
    ("    a[4] = 7 ;",              NO_ERROR,       ""),
    ("    printf(hello world\\n) ;", SYNTAX_ERROR,   "Missing quotes"),
    ("}",                           TYPE_ERROR,     "missing return statement"),
)

CHOICES = (
    (NO_ERROR,"no error"),
    (SYNTAX_ERROR, "syntax error"),
    (TYPE_ERROR, "type error"),
    (RUNTIME_ERROR, "runtime error"),)

class LineField(forms.ChoiceField):
    def __init__(self, code, answer, tips):
        super(LineField, self).__init__(
            label = code, widget=forms.RadioSelect(), choices=CHOICES, initial=0,)
        self.code = code
        self.answer = answer
        self.tips = tips

    def validate(self, value):
        print "%s =? %s" % (value,self.answer)
        if self.answer == value:
            return value
        else:
            raise forms.ValidationError("")
        
class ExerciseForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(ExerciseForm, self).__init__(*args, **kwargs)
        for i,(code,answer,tips) in enumerate(CODE_EXO1):
            code = code.replace(" ", "&nbsp;")
            self.fields['line%d' % i] = LineField(code,answer,tips)

class Exercise1(FormView):

    template_name = "week1/exercise1.html"
    form_class = ExerciseForm
    #success_url = '/thanks/'

    def post(self, request, *args, **kwargs):
        """
        Handles POST requests, instantiating a form instance with the passed
        POST variables and then checked for validity.
        """
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        status = None
        print request.POST
        if '_check' in request.POST:
            print form.is_valid()
            status = "check"
        return self.render_to_response(self.get_context_data(form=form, status=status))


    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        return super(ContactView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(Exercise1, self).get_context_data(**kwargs)
        context['code'] = "\n".join(map(lambda x: x[0], CODE_EXO1))
        return context

def exercise1(request):
    now = datetime.datetime.now()
    html = "<html><body>It is now %s.</body></html>" % now
    return HttpResponse(html)

course/templates/base.html
{% load staticfiles %}
{% load active %}
{% load url from future %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>PLT 2012</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="{% static "bootstrap/css/bootstrap.css"%}" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
      .sidebar-nav {
        padding: 9px 0;
      }
    </style>
    <link href="{% static "bootstrap/css/bootstrap-responsive.css"%}" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144"
	  href="{% static "bootstrap/ico/apple-touch-icon-144-precomposed.png"%}">
    <link rel="apple-touch-icon-precomposed" sizes="114x114"
	  href="{% static "bootstrap/ico/apple-touch-icon-114-precomposed.png"%}">
      <link rel="apple-touch-icon-precomposed" sizes="72x72"
	    href="{% static "bootstrap/ico/apple-touch-icon-72-precomposed.png"%}">
      <link rel="apple-touch-icon-precomposed"
	    href="{% static "bootstrap/ico/apple-touch-icon-57-precomposed.png"%}">
      <link rel="shortcut icon"
	    href="{% static "bootstrap/ico/favicon.png"%}">
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-toggle="collapse"
	     data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="{% url 'course:home' %}">PLT 2012</a>
          <div class="nav-collapse collapse">
            <p class="navbar-text pull-right">
              Logged in as <a href="#" class="navbar-link">Username</a>
            </p>
            <ul class="nav">
              <li class="active"><a href="{% url 'course:home' %}">Home</a></li>
              <li><a href="{% url 'info' %}">Course info</a></li>
              <li><a href="{% url 'contact' %}">Contact</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Week 1</li>

	      {% menuitem "course:week1/lecture1" "Introduction" %}
	      {% menuitem "course:week1/lecture2" "Grammars: abstract and concrete syntax" %}
	      {% menuitem "course:week1/exercises" "Exercises" %}
	      {% menuitem "course:week1/lab" "Lab 1" %}
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">

	  {% block 'content' %}
	  {% endblock %}
	</div>
      </div><!--/row-->

      <hr>

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div><!--/.fluid-container-->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="./bootstrap/js/jquery.js"></script>
    <script src="./bootstrap/js/bootstrap-transition.js"></script>
    <script src="./bootstrap/js/bootstrap-alert.js"></script>
    <script src="./bootstrap/js/bootstrap-modal.js"></script>
    <script src="./bootstrap/js/bootstrap-dropdown.js"></script>
    <script src="./bootstrap/js/bootstrap-scrollspy.js"></script>
    <script src="./bootstrap/js/bootstrap-tab.js"></script>
    <script src="./bootstrap/js/bootstrap-tooltip.js"></script>
    <script src="./bootstrap/js/bootstrap-popover.js"></script>
    <script src="./bootstrap/js/bootstrap-button.js"></script>
    <script src="./bootstrap/js/bootstrap-collapse.js"></script>
    <script src="./bootstrap/js/bootstrap-carousel.js"></script>
    <script src="./bootstrap/js/bootstrap-typeahead.js"></script>

  </body>
</html>

course/templates/week1/exercise1.html
{% extends 'base.html' %}
{% load url from future %}
{% load active %}

{% block 'content' %}
<div class="page-header">
  <h1>Exercise on the introduction and grammars</h1>
</div>
<ul class="nav nav-tabs">
  {% menuitem 'course:week1/exercises/1' "Exercise 1" %}
  {% menuitem 'course:week1' "Exercise 2" %}
</ul>	  


<p>The following C code has around six errors (some of them depend on what you
count as an error). Locate the errors and explain at which compiler phase they
are (or should be) revealed.
  
<pre>
/* this is a buggy hello world program */
{{ code }}
</pre>

<form action="." method="POST" accept-charset="utf-8">
<form>
{% csrf_token %}
<table class="table">
  <tr>
    <th>
    <th>No error
    <th>Syntax error
    <th>Type error
    <th>Runtime error
  {% for field in form %}
  <tr>
    <td><code>{{ field.label|safe }}</code>
    {% for choice in field.field.choices %}
    <td>
      <input type="radio" id="id_{{ field.html_name }}_{{ forloop.counter0 }}"
             value="{{ choice.0 }}"
	     {% ifequal field.data choice.0 %}
             checked="checked"
	     {% endifequal %}
             name="{{ field.html_name }}" />
    {% endfor %}
    {% ifequal status "check" %}
    <td>
      {% if field.errors %}<i class="icon-remove"></i>
      {% else %}<i class="icon-ok"></i>{% endif %}
    {% endifequal %}
  {% endfor %}
</table>
<p>
  <button class="btn btn-primary" type="submit" name="_check">Check</button>
</p>
</form>

{% endblock %}

course/templates/week1/exercises.html
{% extends 'base.html' %}

{% block 'content' %}
<div class="page-header">
  <h1>Exercise on the introduction and grammars</h1>
</div>

<h2>Exercise 1</h2>

<p>The following C code has around six errors (some of them depend on what you
count as an error). Locate the errors and explain at which compiler phase they
are (or should be) revealed.
  
<pre>
/* this is a buggy hello world program */
int main ()
{
    int i ;
    int j = k + 1 ;
    int a[] = {1,2,3}
    j = a + 6 ;
    a[4] = 7 ;
    printf(hello world\n) ; 
}</pre>


<form>
<table class="table">
  <tr>
    <th>line
    <th>no error
    <th>syntax error
    <th>type error
    <th>runtime error
  <tr>
    <td><code>int main ()</code>
    <td><input type="radio" name="line1" value="no-error" />
    <td><input type="radio" name="line1" value="no-error" />
    <td><input type="radio" name="line1" value="no-error" />
    <td><input type="radio" name="line1" value="no-error" />
    <td>
  <tr>
    <td><code>{</code>
    <td><input type="radio" name="line1" value="no-error" />
    <td><input type="radio" name="line1" value="no-error" />
    <td><input type="radio" name="line1" value="no-error" />
    <td><input type="radio" name="line1" value="no-error" />
    <td>
  <tr>
    <td><code>&nbsp;&nbsp;&nbsp;&nbsp;int i;</code>
    <td><input type="radio" name="line1" value="no-error" />
    <td><input type="radio" name="line1" value="no-error" />
    <td><input type="radio" name="line1" value="no-error" />
    <td><input type="radio" name="line1" value="no-error" />
    <td>
  <tr>
    <td><code>&nbsp;&nbsp;&nbsp;&nbsp;int j = k + 1;</code>
    <td><input type="radio" name="line1" value="no-error" />
    <td><input type="radio" name="line1" value="no-error" />
    <td><input type="radio" name="line1" value="no-error" />
    <td><input type="radio" name="line1" value="no-error" />
    <td>
  <tr>
    <td><code>&nbsp;&nbsp;&nbsp;&nbsp;int a[] = {1,2,3}</code>
    <td><input type="radio" name="line1" value="no-error" />
    <td><input type="radio" name="line1" value="no-error" />
    <td><input type="radio" name="line1" value="no-error" />
    <td><input type="radio" name="line1" value="no-error" />
    <td>
  <tr>
    <td><code>&nbsp;&nbsp;&nbsp;&nbsp;j = a + 6 ;</code>
    <td><input type="radio" name="line1" value="no-error" />
    <td><input type="radio" name="line1" value="no-error" />
    <td><input type="radio" name="line1" value="no-error" />
    <td><input type="radio" name="line1" value="no-error" />
    <td>
  <tr>
    <td><code>&nbsp;&nbsp;&nbsp;&nbsp;a[4] = 7 ;</code>
    <td><input type="radio" name="line1" value="no-error" />
    <td><input type="radio" name="line1" value="no-error" />
    <td><input type="radio" name="line1" value="no-error" />
    <td><input type="radio" name="line1" value="no-error" />
    <td>
  <tr>
    <td><code>&nbsp;&nbsp;&nbsp;&nbsp;printf(hello world\n) ;</code>
    <td><input type="radio" name="line1" value="no-error" />
    <td><input type="radio" name="line1" value="no-error" />
    <td><input type="radio" name="line1" value="no-error" />
    <td><input type="radio" name="line1" value="no-error" />
    <td>
  <tr>
    <td><code>}</code>
    <td><input type="radio" name="line1" value="no-error" />
    <td><input type="radio" name="line1" value="no-error" />
    <td><input type="radio" name="line1" value="no-error" />
    <td><input type="radio" name="line1" value="no-error" />
    <td>
</table>
      
  
</form>


<h2>Exercise 2</h2>
<p>Decode the following representation of a JVM program to show (a) the
    corresponding assembly code and (b) a Java expression from which it can be
    obtained.

<pre>0001 0000 1111 1111 0001 0000 0010 0000
0110 0000 0001 0000 0000 1001 0110 1000</pre>
All these codes can be found in Lecture 1. The full set of codes can be found in
    the on-line JVM specification in
    http://java.sun.com/docs/books/vmspec/2nd-edition/html/Instructions2.doc.html

<h2>Exercise 3</h2>
<p>Show the parse tree and abstract syntax tree of the following statement in
  the grammar constructed in Lecture 2.</p>

<pre>while (x > y) y = x = x + 3 ;</pre>

<h2>Exercise 4</h2>
<p>BNFC translates the separator macro into three rules, as follows:

<pre>
                            [Exp] ::= ;
separator Exp "," ;  --->   [Exp] ::= Exp ;
                            [Exp] ::= Exp "," [Exp] ;</pre>

<p>The resulting grammar, however, is not quite accurate. Why? Design a
  different translation that would solve the problem.</p>

<h2>Exercise 5</h2>
<p>Implement a parser for Lisp in BNFC. It should be able to parse the code
  example in <a href="
  http://lib.store.yahoo.net/lib/paulgraham/jmc.lisp">http://lib.store.yahoo.net/lib/paulgraham/jmc.lisp</a>
  – which is actually a complete Lisp interpreter!</p>
{% endblock %}

course/templates/week1/lab-test-suite.html
{% extends 'base.html' %}
{% load url from future %}

{% block 'content' %}
<div class="page-header">
  <h1>Lab 1: Parser for C++ <small>deadline: 2012-02-01</small></h1>
</div>

<ul class="nav nav-tabs">
  <li><a href="{% url 'course:week1/lab' %}">Lab PM</a></li>
  <li class="active"><a href="{% url 'course:week1/lab/test-suite' %}">Test suite</a></li>
  <li><a href="{% url 'course:week1/lab/submit' %}">Submission</a></li>
</ul>	  

<h2>Introduction</h2>

<p>Before you submit lab 1, your solution must pass the testsuite. This document
describes how to obtain and use this testsuite.

<p>The testsuite has now been extended with more good and bad test
programs, and more tests will be added continously. This is done as a service to
you, so that you can check your solution before submitting it. The old
lab1-testsuite.tar.gz is still available, but please use the new one as
described below.

<h2>Preparations</h2>

<p>You will only need to do this this part once.

<ul>
<li>Download lab1-testsuite-larger.tar.gz.
<li>Unpack the downloaded file:
  <pre>$ tar -zxf lab1-testsuite-larger.tar.gz</pre>
<li>Enter the lab1-testsuite-larger directory:
  <pre>$ cd lab1-testsuite-larger</pre>
<li>Compile the test program:
  <ptr>$ ghc --make -o progs-test-lab1 progs-test-lab1.hs</pre>
</ul>

<h2>Running the testsuite</h2>

<p>This is what you need to do to test your grammar.

<ul>
<li>Enter the lab1-testsuite-larger directory (if you are not there already):
  <pre>$ cd lab1-testsuite-larger</pre>
<li>Run the progs-test-lab1 with the path to your .cf file:
  <pre>$ ./progs-test-lab1 path/to/your/file.cf</pre>
(where path/to/your/file.cf) is the location of your grammar file.
</ul>

<p>NOTE: The start category (entry point) of your grammar must be called Program.
{% endblock %}

course/templates/week1/lecture1.html
{% extends 'base.html' %}

{% block 'content' %}
<div class="page-header">
  <h1><small>Lecture 1:</small> Introduction</h1>
</div>

<dl>
  <dt>Reading:
  <dd>Chapter 1 of the book
</dl>
{% endblock %}

course/templates/week1/lecture2.html
{% extends 'base.html' %}

{% block 'content' %}
<div class="page-header">
  <h1><small>Lecture 2:</small> Grammars: abstract and concrete syntax</h1>
</div>

<dl>
  <dt>Reading:
  <dd>Chapter 2 of the book
</dl>
{% endblock %}